version: "3.5"

services:
  mongo:
    container_name: local_mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - local_mongo:/data/db
    ports:
      - 27017:27017
    networks:
      - local_mongo_net
    restart: always

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
      - local_mongo_net

networks:
  local_mongo_net:
    driver: bridge

volumes:
  local_mongo:
